### ISSUE TITLE
[Feature Review] Capitalized letters in Credential Definition and Attribute Names

### ISSUE THREAD

**Issue by PatStLouis** [bcgov/traction#618] opened 2023-05-28 00:25 UTC
When using camelCase naming convention, Credential Definition names and Schema Attribute names get a space prepended to them, resulting in anomalies when responding to a presentation request from the BC Wallet app.

`MyTag` would become `My Tag` in the wallet and `MyAttribute` would become `My Attribute`. The wallet is then having a hard time responding to presentation requests based on those values as restrictions/attribute names.

Is this string manipulation introduced in the Traction app or on the Bifold/BC Wallet app?

**Comment by swcurran** [comment] 2023-05-28 16:05
The Bifold/BC Wallet specifically expands the CamelCase for display purposes (putting text on a screen), but does not do anything that would affect the processing of the AnonCreds objects — credentials, presentations.  Did you note the changes anywhere other than on the Wallet display?

What anomalies occured that might be traced to this behaviour?

**Comment by hiteshgh** [comment] 2023-06-21 17:00
as per above comments from @swcurran looks like this is expected behaviour and not an issue/bug , closing

**Closed by hiteshgh** 2023-06-21 17:00 UTC
