### ISSUE TITLE
Enhancements to tenant logging

### ISSUE THREAD

**Issue by esune** [bcgov/traction#1037] opened 2024-03-04 18:37 UTC
Currently, each log statement generated by a tenant in a multi-tenant instance of ACA-Py is prefixed with the tenant's `wallet_id` - see [here](https://github.com/hyperledger/aries-cloudagent-python/blob/ef204a504083af69d1958daed7da5b5919e3763a/aries_cloudagent/config/logging.py#L52-L53) and [here](https://github.com/hyperledger/aries-cloudagent-python/blob/ef204a504083af69d1958daed7da5b5919e3763a/aries_cloudagent/config/default_per_tenant_logging_config.ini#L27).

For Traction, however, we would like to use the `tenant_id` rather than the `wallet_id` to identify a tenant: this is because of the desire to move towards not exposing a tenant's root credentials for managed wallets.

We need a custom log handler class that will allow to use `tenant_id` as log statement identifier.

**Comment by ianco** [comment] 2024-03-04 20:01
Is this for traction or aca-py?  It sounds like the issue is with log messages that are logged by aca-py, but does aca-py know the tennant_id?

**Comment by esune** [comment] 2024-03-04 20:10
> Is this for traction or aca-py? It sounds like the issue is with log messages that are logged by aca-py, but does aca-py know the tennant_id?

This is for Traction, ACA-Py has no knowledge of the `tenant_id` as it is used internally by the innkeeper plugin.

**Comment by swcurran** [comment] 2024-03-04 21:27
I’m wondering if this needs to be in the logs.  I assume we’ll need a splitter for the logs and that could handle the walletId to tenant_id correspondence.  The walletId could be removed from the logs as part of the splitting.

**Comment by esune** [comment] 2024-03-04 22:21
It would be easier to have ACA-Py log the tenant id rather than having to maintain a service with the mapping to reconcile the logs - if I understand correctly what you mean. If the tenant id is already in the logs, we only need a filter to remove any non-relevant information.

My idea would be to make it possible for a service to serve the "sanitized" logs to each tenant (similar to what OpenShift does with pods) rather than have the operations team fish them out, sanitize them and send them back to each tenant who requested it.

**Comment by WadeBarnes** [comment] 2024-03-05 13:49
Could the logging in ACA-Py be extended to allow a plugin, like traction's innkeeper plugin, to specify (inject) the identifier it wants to use for a tenant's logs rather than hard coding the wallet id as the identifier?  Wallet id could be used as the default if nothing else is supplied.

**Comment by esune** [comment] 2024-03-05 17:25
> Could the logging in ACA-Py be extended to allow a plugin, like traction's innkeeper plugin, to specify (inject) the identifier it wants to use for a tenant's logs rather than hard coding the wallet id as the identifier? Wallet id could be used as the default if nothing else is supplied.

That's what we need to figure out. If the innkeeper plugin can inject its own log handler implementation then we should be good. I guess this issue needs some investigation to understand what is/isn't possible before choosing a direction.

**Comment by esune** [comment] 2024-03-05 17:27
> 
> I’m certainly not suggesting we need any manual intervention.

I misread the comment then, I thought you meant we keep "status-quo" for logs to be served by the ops team when requested.

**Comment by amanji** [comment] 2024-04-22 15:43
Resolved by: #1065

**Closed** 2024-06-06 21:53 UTC
